version: "3.9"

networks:
  public:
    external: true

configs:
  filer:
    file: ./filer.sh
  master:
    file: ./master.toml
  s3:
    file: ./s3.json
  volume:
    file: ./volume.sh

x-volume: &volume
  image: chrislusf/seaweedfs:latest
  environment:
    - HOST={{.Node.Hostname}}
  entrypoint: sh /volume.sh
  networks:
    - public
  volumes:
    - /mnt/seaweedfs/volume:/data
  configs:
    - source: volume
      target: /volume.sh

services:
  master:
    image: chrislusf/seaweedfs:latest
    command:
      - "master"
      - "-volumeSizeLimitMB=1024"
      - "-garbageThreshold=0.01"
      - "-mdir=/data"
    networks:
      - public
    volumes:
      - /mnt/seaweedfs/master:/data
    configs:
      - source: master
        target: /etc/seaweedfs/master.toml
    deploy:
      update_config:
        order: start-first
      placement:
        max_replicas_per_node: 1

  filer:
    image: chrislusf/seaweedfs:latest
    environment:
      - HOST={{.Node.Hostname}}
    entrypoint: sh /filer.sh
    networks:
      - public
    volumes:
      - /mnt/seaweedfs/filer:/data/filerdb
    configs:
      - source: filer
        target: /filer.sh
      - source: s3
        target: /etc/seaweedfs/s3.json
    deploy:
      replicas: 2
      placement:
        max_replicas_per_node: 1

  volume1:
    <<: *volume
    deploy:
      placement:
        constraints:
          - "node.hostname == node1"
  volume2:
    <<: *volume
    deploy:
      placement:
        constraints:
          - "node.hostname == node2"
  volume3:
    <<: *volume
    deploy:
      placement:
        constraints:
          - "node.hostname == node3"
  volume4:
    <<: *volume
    deploy:
      placement:
        constraints:
          - "node.hostname == node4"
